#!/usr/bin/env bash

: ${LDAP_BASEDN:='dc=exemplo'}
: ${LDAP_ROOTPW:='secret'}
: ${LDAP_URLS:='ldapi:/// ldaps:/// ldap:///'}
: ${LDAP_CONFDIR:='/etc/ldap/slapd.d/'}
: ${LDAP_DATA:='/var/lib/ldap/'}
: ${LDAP_DEBUG:='1'}
: ${LDAP_SYNCUSER:='sync'}
: ${LDAP_SYNCUSERPW:='password'}
: ${LDAP_SERVERID:='0'}

chown -R openldap: ${LDAP_CONFDIR} ${LDAP_DATA}
ROOTPW=$(slappasswd -s "${LDAP_ROOTPW}")
SYNCPW=$(slappasswd -s "${LDAP_SYNCUSERPW}")

echo -n "==> Setting configuration ... "
slapd -u openldap -g openldap -h "ldapi:///" -F "${LDAP_CONFDIR}" && echo "exit error" || exit 1
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ${LDAP_BASEDN}
-
replace: olcRootDN
olcRootDN: cn=admin,${LDAP_BASEDN}
-
replace: olcRootPW
olcRootPW: ${ROOTPW}
-
replace: olcDbDirectory
olcDbDirectory: ${LDAP_DATA}
-
replace: olcDbIndex
olcDbIndex: cn pres,sub,eq
-
add: olcDbIndex
olcDbIndex: sn,ou pres,sub,eq
-
add: olcDbIndex
olcDbIndex: uid pres,sub,eq
-
add: olcDbIndex
olcDbIndex: displayName pres,sub,eq
-
add: olcDbIndex
olcDbIndex: default sub
-
add: olcDbIndex
olcDbIndex: uidNumber eq
-
add: olcDbIndex
olcDbIndex: gidNumber eq
-
add: olcDbIndex
olcDbIndex: mail,givenName eq,subinitial
-
add: olcDbIndex
olcDbIndex: dc eq
-
add: olcDbIndex
olcDbIndex: objectClass,entryCSN,entryUUID eq,pres
-
add: olcDbIndex
olcDbIndex: sudoUser eq
-
delete: olcAccess
olcAccess: {0}to attrs=userPassword by self write by anonymous auth by * none
-
add: olcAccess
olcAccess: {0}to attrs=userPassword,shadowLastChange by self write by anonymous auth by dn="cn=admin,${LDAP_BASEDN}" write by dn="cn=${LDAP_SYNCUSER},${LDAP_BASEDN}" read by * none
EOF

ldapmodify -D "cn=admin,${LDAP_BASEDN}" -w "${ROOTPW}" <<EOF
dn: cn=${LDAP_SYNCUSER},${LDAP_BASEDN}
changetype: add
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: ${LDAP_SYNCUSER}
description: Syncrepl user for mirrormode operation
userPassword: ${SYNCPW}
EOF

ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: syncprov
EOF

ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: olcOverlay=syncprov,olcDatabase={1}hdb,cn=config
changeType: add
objectClass: olcOverlayConfig
objectClass: olcSyncProvConfig
olcOverlay: syncprov
olcSpCheckpoint: 100 10
olcSpSessionLog: 100
EOF

ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changeType: modify
add: olcServerID
olcServerID: ${LDAP_SERVERID}
EOF

kill $(cat /run/slapd/slapd.pid)
echo "Done"

echo "==> Starting slapd"
slapd -u openldap -g openldap -h "${LDAP_URLS}" -F ${LDAP_CONFDIR} -d ${LDAP_DEBUG}
