version: "3.7"

services:

  slapd:
    image: glenonmateus/slapd
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    ports:
    - 389:389
    - 636:636
    environment:
    - LDAP_BASEDN=o=FUMEC
    - LDAP_ROOTPW=password
    - LDAP_TLSCACERTFILE=/etc/ldap/certs/ca_server.pem
    - LDAP_TLSCERTFILE=/etc/ldap/certs/ldap_server.pem
    - LDAP_TLSCERTKEYFILE=/etc/ldap/private/ldap_server.key
    volumes:
    - slapd_conf:/etc/ldap/
    - slapd_lib:/var/lib/ldap/

volumes:
  slapd_conf:
  slapd_lib:
