version: "3.7"

services:

  slapd:
    image: glenonmateus/slapd
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    ports:
    - 389:389
    environment:
    - LDAP_BASEDN=o=FUMEC
    - LDAP_ROOTPW=password
    volumes:
    - slapd_conf:/etc/ldap/
    - slapd_lib:/var/lib/ldap/
    networks:
    - slapd

volumes:
  slapd_conf:
    #    driver: local
    #driver_opts:
    #  type: "nfs4"
    #  o: "addr=10.0.3.15,rw"
    #  device: ":/docker/slapd_conf"
  slapd_lib:
    #driver: local
    #driver_opts:
    #  type: "nfs4"
    #  o: "addr=10.0.3.15,rw"
    #  device: ":/docker/slapd_lib"

networks:
  slapd:
