#!/bin/bash

: ${LDAP_BASEDN:='dc=exemplo'}
: ${LDAP_ROOTPW:='secret'}
: ${LDAP_URLS:='ldapi:/// ldaps:/// ldap:///'}
: ${LDAP_CONFDIR:='/etc/ldap/slapd.d/'}
: ${LDAP_DATA:='/var/lib/ldap/'}
: ${LDAP_DEBUG:='1'}
: ${LDAP_TLSCACERTFILE:='/etc/ldap/certs/ca_server.pem'}
: ${LDAP_TLSCERTFILE:='/etc/ldap/certs/ldap_server.pem'}
: ${LDAP_TLSCERTKEYFILE:='/etc/ldap/private/ldap_server.key'}

CONFIGS_VARS=(
  LDAP_BASEDN
  LDAP_ROOTPW
  LDAP_URLS
  LDAP_CONFDIR
  LDAP_DEBUG
  LDAP_TLSCACERTFILE
  LDAP_TLSCERTFILE
  LDAP_TLSCERTKEYFILE
)

chown -R openldap: ${LDAP_CONFDIR} ${LDAP_DATA}

echo -n "==> Setting configuration ... "
[ -f "${LDAP_TLSCERTKEYFILE}" ] && chown openldap: ${LDAP_TLSCERTKEYFILE}
slapd -u openldap -g openldap -h "ldapi:///" -F "${LDAP_CONFDIR}" && echo "exit error" || exit 1
ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ${LDAP_BASEDN}
-
replace: olcRootDN
olcRootDN: cn=admin,${LDAP_BASEDN}
-
replace: olcRootPW
olcRootPW: $(slappasswd -s "${LDAP_ROOTPW}")
-
replace: olcDbIndex
olcDbIndex: cn pres,sub,eq
-
add: olcDbIndex
olcDbIndex: sn,ou pres,sub,eq
-
add: olcDbIndex
olcDbIndex: uid pres,sub,eq
-
add: olcDbIndex
olcDbIndex: displayName pres,sub,eq
-
add: olcDbIndex
olcDbIndex: default sub
-
add: olcDbIndex
olcDbIndex: uidNumber eq
-
add: olcDbIndex
olcDbIndex: gidNumber eq
-
add: olcDbIndex
olcDbIndex: mail,givenName eq,subinitial
-
add: olcDbIndex
olcDbIndex: dc eq
-
add: olcDbIndex
olcDbIndex: objectClass eq,pres
EOF

ldapmodify -Y EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
add: olcTLSCACertificateFile
olcTLSCACertificateFile: ${LDAP_TLSCACERTFILE}
-
add: olcTLSCertificateFile
olcTLSCertificateFile: ${LDAP_TLSCERTFILE}
-
add: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: ${LDAP_TLSCERTKEYFILE}
-
add: olsTLSVerifyClient
olsTLSVerifyClient: never
EOF
kill $(cat /run/slapd/slapd.pid)
echo "Done"

echo "==> Starting slapd"
slapd -u openldap -g openldap -h "${LDAP_URLS}" -F ${LDAP_CONFDIR} -d ${LDAP_DEBUG}

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b "cn=config" '(cn=config)' | grep olcTLSCACertificateFile)
if [ ! -z "${LDAP_TLSCACERTFILE}" ] && [ -f "${LDAP_TLSCACERTFILE}" ]
then
    echo "Setting CACertificateFile"
    chown -R openldap: ${LDAP_TLSCACERTFILE}
    chmod 700 ${LDAP_TLSCACERTFILE}
    if [ -z "${OUTPUT}" ]
    then
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
add: olcTLSCACertificateFile
olcTLSCACertificateFile: ${LDAP_TLSCACERTFILE}
EOF
    else
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
replace: olcTLSCACertificateFile
olcTLSCACertificateFile: ${LDAP_TLSCACERTFILE}
EOF
    fi
else
echo "CA Certificate file do not defined or not exist"
fi

set -x
OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b "cn=config" '(cn=config)' | grep olcTLSCertificateFile)
if [ ! -z "${LDAP_TLSCERTFILE}" ] && [ -f "${LDAP_TLSCERTFILE}" ]
then
    echo -n "Setting CertificateFile"
    chown -R openldap: ${LDAP_TLSCERTFILE}
    chmod 700 ${LDAP_TLSCERTFILE}
    if [ -z "$OUTPUT" ]
    then
    echo "adding"
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
add: olcTLSCertificateFile
olcTLSCertificateFile: ${LDAP_TLSCERTFILE}
EOF
    else
    echo "replacing"
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
replace: olcTLSCertificateFile
olcTLSCertificateFile: ${LDAP_TLSCERTFILE}
EOF
    fi
else
echo "Certificate not defined or not exist"
fi
set +x

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b "cn=config" '(cn=config)' | grep olcTLSCertificateKeyFile)
if [ ! -z "${LDAP_TLSCERTKEYFILE}" ] && [ -f "${LDAP_TLSCERTKEYFILE}" ]
then
    echo -n "Setting CertificateKeyFile ... "
    chown -R openldap: ${LDAP_TLSCERTKEYFILE}
    chmod 700 ${LDAP_TLSCERTKEYFILE}
    if [ -z "$OUTPUT" ]
    then
    echo "adding"
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
add: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: ${LDAP_TLSCERTKEYFILE}
EOF
    else
    echo "replacing"
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changetype: modify
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: ${LDAP_TLSCERTKEYFILE}
EOF
    fi
else
echo "Certificate Key not defined or not exist"
fi
