version: "3.7"

services:

  slapd:
    image: glenonmateus/slapd
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
    ports:
    - 389:389
    environment:
    - LDAP_BASEDN=o=FUMEC
    - LDAP_ROOTPW=password
    volumes:
    - slapd_conf:/etc/ldap/
    - slapd_lib:/var/lib/ldap/

volumes:
  slapd_conf:
  slapd_lib:
