#!/usr/bin/env bash

: ${LDAP_BASEDN:='exemplo'}
: ${LDAP_ROOTPW:='secret'}
: ${LDAP_URLS:='ldapi:/// ldaps:/// ldap:///'}
: ${LDAP_CONFDIR:='/etc/ldap/slapd.d/'}
: ${LDAP_DATA:='/var/lib/ldap/'}
: ${LDAP_DEBUG:='1'}
: ${LDAP_SYNCUSER:='sync'}
: ${LDAP_SYNCUSERPW:='password'}
: ${LDAP_SERVERID:='0'}

chown -R openldap: ${LDAP_CONFDIR} ${LDAP_DATA}
ROOTPW=$(slappasswd -s "${LDAP_ROOTPW}")
SYNCPW=$(slappasswd -s "${LDAP_SYNCUSERPW}")

echo "==> Setting configuration ... "
slapd -u openldap -g openldap -h "ldapi:/// ldap:///" -F "${LDAP_CONFDIR}"
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: olcDatabase={1}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: o=${LDAP_BASEDN}
-
replace: olcRootDN
olcRootDN: cn=admin,o=${LDAP_BASEDN}
-
replace: olcRootPW
olcRootPW: ${ROOTPW}
-
replace: olcDbDirectory
olcDbDirectory: ${LDAP_DATA}
-
replace: olcDbIndex
olcDbIndex: cn pres,sub,eq
-
add: olcDbIndex
olcDbIndex: sn,ou pres,sub,eq
-
add: olcDbIndex
olcDbIndex: uid pres,sub,eq
-
add: olcDbIndex
olcDbIndex: displayName pres,sub,eq
-
add: olcDbIndex
olcDbIndex: default sub
-
add: olcDbIndex
olcDbIndex: uidNumber eq
-
add: olcDbIndex
olcDbIndex: gidNumber eq
-
add: olcDbIndex
olcDbIndex: mail,givenName eq,subinitial
-
add: olcDbIndex
olcDbIndex: dc eq
-
add: olcDbIndex
olcDbIndex: objectClass,entryCSN,entryUUID eq,pres
-
add: olcDbIndex
olcDbIndex: sudoUser eq
EOF

ldapmodify -D "cn=admin,o=${LDAP_BASEDN}" -w "${LDAP_ROOTPW}" <<EOF
dn: o=${LDAP_BASEDN}
changetype: add
objectClass: organization
objectClass: top
o: ${LDAP_BASEDN}
EOF

ldapmodify -D "cn=admin,o=${LDAP_BASEDN}" -w "${LDAP_ROOTPW}" <<EOF
dn: cn=${LDAP_SYNCUSER},o=${LDAP_BASEDN}
changetype: add
objectClass: simpleSecurityObject
objectClass: organizationalRole
cn: ${LDAP_SYNCUSER}
description: Syncrepl user for mirrormode operation
userPassword: ${SYNCPW}
EOF

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b 'cn=config' '(cn=module{0})' | grep syncprov)
if [ -z "${OUTPUT}" ]; then
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: syncprov
EOF
fi

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b 'cn=config' dn | grep syncprov)
if [ -z "${OUTPUT}" ]; then
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: olcOverlay=syncprov,olcDatabase={1}mdb,cn=config
changeType: add
objectClass: olcOverlayConfig
objectClass: olcSyncProvConfig
olcOverlay: syncprov
olcSpCheckpoint: 100 10
olcSpSessionLog: 100
EOF
fi

ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=config
changeType: modify
replace: olcServerID
olcServerID: ${LDAP_SERVERID}
EOF

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b "cn=config" '(cn=module{0})' | grep memberof)
if [ -z "${OUTPUT}" ]; then
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: cn=module{0},cn=config
changeType: modify
add: olcModuleLoad
olcModuleLoad: memberof.la
EOF
fi

OUTPUT=$(ldapsearch -QLLL -Y EXTERNAL -H ldapi:/// -b "cn=config" dn | grep memberof)
if [ -z "${OUTPUT}" ]; then
ldapmodify -QY EXTERNAL -H ldapi:/// <<EOF
dn: olcOverlay=memberof,olcDatabase={1}mdb,cn=config
changeType: add
objectClass: olcOverlayConfig
objectClass: olcMemberOf
olcOverlay: memberof
olcMemberOfRefint: TRUE
EOF
fi

kill $(cat /run/slapd/slapd.pid)
echo "Done"

echo "==> Starting slapd"
slapd -u openldap -g openldap -h "${LDAP_URLS}" -F ${LDAP_CONFDIR} -d ${LDAP_DEBUG}
