#!/usr/bin/env bash

LASTUIDNUMBER=$(ldapsearch -h 127.0.0.1 -LLL -x -D "cn=admin,o=fumec" -w'password'  -b "o=fumec" "(objectClass=inetOrgPerson)" uidNumber | grep -i uidNumber | cut -d' ' -f2 | sort -h | tail -n1)
LASTGIDNUMBER=$(ldapsearch -h 127.0.0.1 -LLL -x -D "cn=admin,o=fumec" -w'password'  -b "o=fumec" "(objectClass=inetOrgPerson)" gidNumber | grep -i gidNumber | cut -d' ' -f2 | sort -h | tail -n1)

usage() {
cat <<EOF

Usage: $0 [ -b BASE ] [ -i INPUT_CSVFILE ] [ -o OUTPUT_LDIFFILE ]

Options:
  -b      ldap base
  -i      input csv file (delimiter ,)
  -o      output save ldif file

EOF
}

exit_abnormal() {
  usage
  exit 1
}

create_ldif() {
  echo -n "Creating ldif file ... "
  sed 1d $INPUT | while IFS=, read LOGIN NOME EMAIL EMAILOUTRO CELULAR TELEFONE CURSO
    do
      LASTUIDNUMBER=$(expr $LASTUIDNUMBER + 1)
      NOME=$(echo $NOME | iconv -f utf8 -t ascii//TRANSLIT)
      PASSWORD=$(mkpasswd -m sha-512 $LOGIN)

cat <<EOF >> $OUTPUT
dn: uid=$LOGIN,$BASE
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: posixAccount
objectClass: shadowAccount
objectClass: sambaSamAccount
objectClass: top
cn: $LOGIN
homeDirectory: /home/LAN/$LOGIN
sambaSID: \$SAMBAUID\$
sambaAcctFlags: [U]
sn: $LOGIN
uid: $LOGIN
uidNumber: $LASTUIDNUMBER
gidNumber: 100019
displayName: $LOGIN
gecos: $NOME
givenName: $LOGIN
loginShell: /bin/false
mail: $EMAIL
$([ ! -z "$CELULAR" ] && echo "telephoneNumber: $CELULAR")
$([ ! -z "$TELEFONE" ] && echo "telephoneNumber: $TELEFONE")
userPassword: {CRYPT}$PASSWORD

EOF

    done
  echo "Done"
}

while getopts "b:i:o:" OPTION
do
  case $OPTION in
    b) BASE=${OPTARG} ;;
    i) INPUT=${OPTARG} ;;
    o) OUTPUT=${OPTARG} ;;
    *) exit_abnormal ;;
  esac
done

if [ -z "$BASE" ] || [ -z "$INPUT" ] || [ -z "$OUTPUT" ] ; then
  exit_abnormal
fi

if [ -f "$OUTPUT" ]; then
  read -p "File $OUTPUT already exist, overwrite? (y/n): " OPTION
  case $OPTION in
    y | Y)
      > $OUTPUT
      create_ldif
      exit 0
      ;;
    n | N)
      exit 0
      ;;
    *)
      echo "Invalid option"
      exit 0
      ;;
  esac
fi

create_ldif
